export interface Driver {
    firstName?: string,
    lastName?: string,
    email?: string,
    nic?: string,
    birthday?: Date,
    mobile?: string,
    gender?: string,
    address?: string,
    street?: string,
    city?: string,
    zipcode?: number,
    country?: string,
    nicFrontPic?: any,
    nicBackPic?: any,
    drivingLicenceFrontPic?: any,
    drivingLicenceBackPic?: any,
    lifeInsuranceNo?: string,
    stringExpiryDate?: Date,
    driverPic?: any,
    lifeInsuranceAmount?: number,
    lifeInsuranceExpiryDate?:Date,
    driverId?:string
}
